### PR TITLE
fix: remove client file,

### PR DESCRIPTION
**Pull request by xiagw**

### CODE REVIEW

**Review by randomshell — COMMENTED** [review]
This might also work but I didn't want to duplicate the code for the home directory.

**Comment by xiagw** [comment]
> This might also work but I didn't want to duplicate the code for the home directory.

But there will be a problem here
You can put this piece of code in the global

**Comment by hellresistor** [comment]
Can I suggest this?

"Not delete. But put inside of a RemovedClients folder" ?

**Comment by angristan** [comment]
Properly fixed with https://github.com/angristan/wireguard-install/commit/7565f26b5d2e4542f777001859970378704ce288

**Pull request closed without merging**
