### PR TITLE
Minor changes on the install

### PR DESCRIPTION
**Pull request by liberodark**
Somes changes of WireGuard Install

### CODE REVIEW

**Comment by liberodark** [comment]
Vous parlez français on dirait donc je vous fécilite pour la qualité du script c'est vraiment bien.
J'ai commencé à travailler sur une version pour ajouter des clients supplémentaires.

--------------

You speak French, so it looks like I would be very happy for the quality of the script, it's really good.
I started working on a version to add additional clients.

**Comment by realcarbonneau** [comment]
Oui, super, je suis billingue, Français and English.  En espérant d'avoir des méthodes simple pour ajouter des clients dynamiquements et rapidements! :)

**Comment by liberodark** [comment]
Je tente de fermer plusieurs issues.
J'ai commencé à retravailler le script pour que ce soit plus modulaire.

-----------------------------------

I am trying to close several issues.
I started to rework the script to make it more modular.

**Comment by liberodark** [comment]
Im happy to send my new work : 
image
This release is stable and work better.
But with time im go to add more fonctionnality.

**Comment by liberodark** [comment]
You have possibility to add on your repo now.
Have the last issue #48

**Comment by Prajwal-Koirala** [comment]
code quality is terrible.

**Comment by liberodark** [comment]
@Prajwal-Koirala Ok explain that ?
What is bad in my work my open to improve if you have suggest.

Best Regards

**Comment by Prajwal-Koirala** [comment]
Hey,

Check this out.

https://github.com/complexorganizations/wireguard-install

Functions, Structured code, Clean Code, Not confusing to read.

- Prajwal

**Comment by angristan** [comment]
Sorry, this is impossible to review, there are way too many changes (contrary to what the title says haha). Please break it down to multiple tiny PRs if possible, thanks!

**Comment by liberodark** [comment]
> Sorry, this is impossible to review, there are way too many changes (contrary to what the title says haha). Please break it down to multiple tiny PRs if possible, thanks!

Hi the better for me and you is make a new branch.
If you have possibility to add my on your project for work on the new branch that would be good for help.
And you make a pr from this branch later in master.
Does that suit you?

Best Regards

**Comment by randomshell** [comment]
Any updates here? This PR solves many issues and refactors some code so I think it is better to merge this before working on other issues.

@liberodark Can you split the commits in to smaller changes and possible with a meaningful title please? It would really be easier to understand and review.

**Comment by liberodark** [comment]
that make many work for nothing to split is bash and fonction is very easy to read the change.
No have bigger time for make little change by little change i dont understand this why need to split...
But other solution is to put on other branch is more simple not ?

**Comment by xsoheilalizadeh** [comment]
@angristan Would you mind merg this PR please?

**Comment by angristan** [comment]
As said before, although I am very grateful for the contribution, there are to many changes in that pull request.

- This makes it very difficult to review
- Not all changes might be accepted
- Not all changes might work

**Comment by HLFH** [comment]
@angristan I don't think this PR is properly squashed, documented, split.

Best to close the PR in the mean time and wait for more organised PRs?

**Pull request closed without merging**
