### PR TITLE
Add contributors hall-of-fame

### LINKED ISSUE #89: Add contributors hall-of-fame
@angristan can you add https://github.com/sourcerer-io/hall-of-fame/ as you did on the openvpn-install repo?

### PR DESCRIPTION
**Pull request by angristan**
Still generating atm

Fix #89

### CODE REVIEW

**Comment by robiiinos** [comment]
Can you update the README for PulseHeberg which instances starts at 4€ / month now ?

**Comment by angristan** [comment]
I think sourcerer.io is broken :(

**Comment by randomshell** [comment]
You enabled the repository in sourcerer.io settings, right?

**Comment by angristan** [comment]
Yes, to no avail. `openvpn-install` does not update either.

screenshot_2020-07-25_13-29-03@2x

**Comment by angristan** [comment]
I contacted sourcerer and they told me to open an issue: https://github.com/sourcerer-io/hall-of-fame/issues/48

**Comment by angristan** [comment]
Will reopen once/if sourcerer is fixed.

**Comment by angristan** [comment]
If you know of any alternative, let me know :)

**Comment by randomshell** [comment]
A great one that works with non-code contributions too is https://github.com/all-contributors/all-contributors

**Comment by angristan** [comment]
Agreed, seems like an even better one

**Comment by angristan** [comment]
https://github.com/angristan/wireguard-install/pull/113

**Pull request closed without merging**
