### PR TITLE
Add support for Rocky linux distribution

### PR DESCRIPTION
**Pull request by pinokaille**

### CODE REVIEW

**Comment by angristan** [comment]
Doesn't work for me:

```
[root@scw-elastic-brahmagupta ~]# dnf install -y wireguard-dkms
Copr repo for wireguard owned by jdoss                                                                     13 kB/s | 3.3 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides dkms needed by wireguard-dkms-1:1.0.20210606-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by pinokaille** [comment]
> Doesn't work for me:
> 
> ```
> [root@scw-elastic-brahmagupta ~]# dnf install -y wireguard-dkms
> Copr repo for wireguard owned by jdoss                                                                     13 kB/s | 3.3 kB     00:00
> Error:
>  Problem: conflicting requests
>   - nothing provides dkms needed by wireguard-dkms-1:1.0.20210606-2.el8.noarch
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```

you need dkms to install wireguard if you have a lxc vps this is not possible you need a kvm vps

**Comment by angristan** [comment]
This was a KVM VM :)

**Comment by mattvx** [comment]
I've managed to run installation script on a rocky linux AWS EC2 istance with no problem at all.
it works like a charm.

Rocky is bug to bug compatible with CentOS 8 so the script does the OS check without issues, as in rocky's /etc/ dir you have the "centos-release" file.

the only error that did absolutely not affect installation or performance was an error raised by line 147 on the installation script.
Rocky version i tested was 8.4, and the error states:

"[[: 8.4: syntax error: invalid arithmetic operator (error token is ".4""

**Comment by angristan** [comment]
That would be this line:

```sh
elif [[ ${OS} == 'rocky' ]]; then
```

**Comment by angristan** [comment]
This PR still doesn't work for me:

```
+ dnf install -y wireguard-dkms
Copr repo for wireguard owned by jdoss                                                            12 kB/s | 3.3 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides dkms needed by wireguard-dkms-1:1.0.20210606-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

```
[root@scw-confident-shtern ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by mattvx** [comment]
> This PR still doesn't work for me:
> 
> ```
> + dnf install -y wireguard-dkms
> Copr repo for wireguard owned by jdoss                                                            12 kB/s | 3.3 kB     00:00
> Error:
>  Problem: conflicting requests
>   - nothing provides dkms needed by wireguard-dkms-1:1.0.20210606-2.el8.noarch
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```
> 
> ```
> [root@scw-confident-shtern ~]# cat /etc/os-release
> NAME="Rocky Linux"
> VERSION="8.4 (Green Obsidian)"
> ID="rocky"
> ID_LIKE="rhel fedora"
> VERSION_ID="8.4"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
> ANSI_COLOR="0;32"
> CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
> HOME_URL="https://rockylinux.org/"
> BUG_REPORT_URL="https://bugs.rockylinux.org/"
> ROCKY_SUPPORT_PRODUCT="Rocky Linux"
> ROCKY_SUPPORT_PRODUCT_VERSION="8"
> ```

`[rocky@ip-172-31-11-255 ~]$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"`

`rocky@ip-172-31-11-255 ~]$ uname -a
Linux ip-172-31-11-255.us-east-2.compute.internal 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Thu Jun 17 07:52:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mattvx** [comment]
> This PR still doesn't work for me:
> 
> ```
> + dnf install -y wireguard-dkms
> Copr repo for wireguard owned by jdoss                                                            12 kB/s | 3.3 kB     00:00
> Error:
>  Problem: conflicting requests
>   - nothing provides dkms needed by wireguard-dkms-1:1.0.20210606-2.el8.noarch
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```
> 
> ```
> [root@scw-confident-shtern ~]# cat /etc/os-release
> NAME="Rocky Linux"
> VERSION="8.4 (Green Obsidian)"
> ID="rocky"
> ID_LIKE="rhel fedora"
> VERSION_ID="8.4"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
> ANSI_COLOR="0;32"
> CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
> HOME_URL="https://rockylinux.org/"
> BUG_REPORT_URL="https://bugs.rockylinux.org/"
> ROCKY_SUPPORT_PRODUCT="Rocky Linux"
> ROCKY_SUPPORT_PRODUCT_VERSION="8"
> ```

@angristan  Sorry! with the first comment i meant with your script: "angristan/wireguard-install", not this PR one.

Being Rocky 1:1 with CentOS, there is no need to add "rocky linux support" as is already supported by original release.
I'm new here... apologize me! @

**Comment by angristan** [comment]
Oh, ok, I see. thanks

**Pull request closed without merging**
