### PR TITLE
Run `systemctl enable` before `systemctl start`

### PR DESCRIPTION
**Pull request by randomshell**
https://github.com/angristan/openvpn-install/commit/44105eb06068ef95ff3217924ee615e8757f7516

Not an issue for now but best practice.

### CODE REVIEW

**Comment by angristan** [comment]
> best practice.

Source?

**Comment by randomshell** [comment]
> > best practice.
> 
> Source?

Just https://github.com/angristan/openvpn-install/commit/44105eb06068ef95ff3217924ee615e8757f7516 :smile:

**Comment by angristan** [comment]
Well that's not a best practice then. 😉 Probably an undocumented behavior. 🤷‍♂ 

If I'm not mistaken, we don't have any issue of that kind with this repo, and we don't patch the unit file.

**Comment by randomshell** [comment]
Ok, closing.

**Pull request closed without merging**
